name: whats_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.3

  
  # state management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  # helper packages
  equatable: ^2.0.5

  # di
  get_it: ^7.6.4

  # validation
  formz: ^0.6.1

  # get image from gallary
  image_picker: ^1.0.4
  path_provider: ^2.1.1

  # permisstion
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.7+1
  uuid: ^4.1.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Droid
      fonts:
        - asset: assets/fonts/Droid_Arabic.ttf
  assets:
    - assets/data/
    - assets/images/
