// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzj2nieQj4SfbXfFYzlsa-Z7Hcj3rwpf0',
    appId: '1:666826650748:web:73a4a67da0992b8702c5f9',
    messagingSenderId: '666826650748',
    projectId: 'whatsapp-b5670',
    authDomain: 'whatsapp-b5670.firebaseapp.com',
    storageBucket: 'whatsapp-b5670.appspot.com',
    measurementId: 'G-ZJYYVM4JCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChDwDnrNBG8CbmsSNd6SefCulxUVYWghg',
    appId: '1:666826650748:android:0049e7b1e9dd2c3902c5f9',
    messagingSenderId: '666826650748',
    projectId: 'whatsapp-b5670',
    storageBucket: 'whatsapp-b5670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjphoOMcqlv_YRAVUNXFD9Hv_N0DSTd48',
    appId: '1:666826650748:ios:81794dc5855855d502c5f9',
    messagingSenderId: '666826650748',
    projectId: 'whatsapp-b5670',
    storageBucket: 'whatsapp-b5670.appspot.com',
    androidClientId: '666826650748-g0hui1ufb9t35khis5sg2pc0dmmud1q8.apps.googleusercontent.com',
    iosClientId: '666826650748-50f16h24s6qaijmq95krrj3rb1mai6vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );
}
