// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwEuFiPX6_m8RepP5CueXNrpc83cXVTMg',
    appId: '1:461211317713:web:fad802c9d98988b5f25cf0',
    messagingSenderId: '461211317713',
    projectId: 'whats-app-b992d',
    authDomain: 'whats-app-b992d.firebaseapp.com',
    storageBucket: 'whats-app-b992d.appspot.com',
    measurementId: 'G-GXEFQVSRCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1iQlHIGIGXocubLaAvkJdPlsZQzRBjTE',
    appId: '1:461211317713:android:7152bf8d7cbb8e3cf25cf0',
    messagingSenderId: '461211317713',
    projectId: 'whats-app-b992d',
    storageBucket: 'whats-app-b992d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZHyPurrGRodXqx2sqxTFbf0CqeTZ5pQ',
    appId: '1:461211317713:ios:c9ae719f534a4281f25cf0',
    messagingSenderId: '461211317713',
    projectId: 'whats-app-b992d',
    storageBucket: 'whats-app-b992d.appspot.com',
    iosClientId: '461211317713-nih4nvudu5trplrfssuv4f7qasgjbme8.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );
}
